/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Arena(props) {
  const { nodes, materials } = useGLTF("/CablecraftV2.glb");
  materials.Floor.visible = true;
  console.log(materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        visible={false}
        geometry={nodes.Cube.geometry}
        material={materials.WallMat}
        position={[-0.036, -0.021, -0.76]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table.geometry}
        material={materials["Material.002"]}
        position={[3.887, 0.907, -1.836]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Material}
        position={[5.27, 0.429, 0.981]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Material}
        position={[2.355, 0.429, 4.225]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
        position={[-2.033, 0.429, 4.225]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[-6.422, 0.429, 4.225]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion001.geometry}
        material={materials["Chair Cushion"]}
        position={[0.583, 0.504, 1.675]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal001.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Material}
        position={[2.355, 0.429, -5.304]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.Material}
        position={[-2.033, 0.429, -5.304]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.Material}
        position={[-6.422, 0.429, -5.304]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials.Material}
        position={[5.27, 0.429, -2.931]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials.Floor}
        position={[-0.036, -0.023, -0.76]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials.Material}
        position={[1.486, 0.429, 1.05]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.016, 1, 0.506]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.Material}
        position={[1.486, 0.429, -2.367]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.016, 1, 0.506]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials.Material}
        position={[1.054, 0.61, -0.902]}
        scale={[0.016, 0.539, 1.859]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials.Material}
        position={[-2.812, 0.429, 0.671]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.016, 1, 3.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials.Material}
        position={[-2.812, 0.429, -1.973]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.016, 1, 3.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.Material}
        position={[-0.463, 0.429, 0.589]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials.Material}
        position={[-0.463, 0.429, -1.996]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.Material}
        position={[-2.89, 0.429, 0.589]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials.Material}
        position={[-2.89, 0.429, -1.996]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials.Material}
        position={[-5.345, 0.429, 0.589]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.Material}
        position={[-5.345, 0.429, -1.996]}
        scale={[0.016, 1, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion002.geometry}
        material={materials["Chair Cushion"]}
        position={[-0.917, 0.504, 1.675]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal002.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion003.geometry}
        material={materials["Chair Cushion"]}
        position={[-2.417, 0.504, 1.675]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal003.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion004.geometry}
        material={materials["Chair Cushion"]}
        position={[-3.917, 0.504, 1.675]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal004.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion005.geometry}
        material={materials["Chair Cushion"]}
        position={[-5.417, 0.504, 1.675]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal005.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion006.geometry}
        material={materials["Chair Cushion"]}
        position={[-5.417, 0.504, -2.885]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal006.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion007.geometry}
        material={materials["Chair Cushion"]}
        position={[-3.917, 0.504, -2.885]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal007.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion008.geometry}
        material={materials["Chair Cushion"]}
        position={[-2.417, 0.504, -2.885]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal008.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion009.geometry}
        material={materials["Chair Cushion"]}
        position={[-0.917, 0.504, -2.885]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal009.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair_Cushion010.geometry}
        material={materials["Chair Cushion"]}
        position={[0.583, 0.504, -2.885]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Chair_Metal010.geometry}
          material={materials["Chair Metal"]}
          position={[0, 0.672, -0.722]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/CablecraftV2.glb");
